### ISSUE TITLE
Reason-Relay seems incompatible with latest graphql package 15.0.0

### ISSUE THREAD

**Issue by sync** [zth/reason-relay#28]
error:

```
Generating ReasonRelay assets...
(node:67882) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '__schema' of undefined
    at generateSchemaAssets (/Users/anthonymittaz/Projects/Startup/pollen-tracker/node_modules/reason-relay/compiler/generateSchemaAssets.js:6:27)
    at /Users/anthonymittaz/Projects/Startup/pollen-tracker/node_modules/reason-relay/compiler/compiler-cli.js:69:9
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:67882) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:67882) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
HINT: pass --watch to keep watching for changes.
```

**Comment by sync** [comment]
You can see issue here:
https://github.com/sync/pollen-tracker

and revert commit: 
09611f4e Downgrade graphql version it seems to be having issue with reason relay

**Comment by zth** [comment]
Thanks for the report! The next release will fix that, will get it out today or tomorrow 👍

**Comment by sync** [comment]
Thanks and no rush 🤗

**Comment by zth** [comment]
`0.7.0` should fix this, please re-open this if it doesn't.
